# Generated by Django 4.2.2 on 2023-07-22 04:32

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_cafe_ticket_delete_post_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafe',
            options={'ordering': ['-publish'], 'verbose_name': 'کافه', 'verbose_name_plural': 'کافه ها'},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام')),
                ('body', models.TextField(verbose_name='متن کامنت')),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('active', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='business.cafe', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
                'ordering': ['created'],
                'indexes': [models.Index(fields=['created'], name='business_co_created_9bf774_idx')],
            },
        ),
    ]
