# Generated by Django 4.2.3 on 2023-08-02 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_cafe_options_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='cafe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='business.cafe', verbose_name='کافه'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='business.cafe', verbose_name='نام و نام خانوادگی')),
            ],
        ),
    ]
