# Generated by Django 4.2.3 on 2023-08-03 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_contactus_email_alter_contactus_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'پیام های کاربر', 'verbose_name_plural': 'پیام های کاربران'},
        ),
    ]
