# Generated by Django 4.2.3 on 2023-08-09 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_contactus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='business.cafe', verbose_name='کافه'),
        ),
    ]
