# Generated by Django 4.2.4 on 2023-08-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_alter_comment_cafe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='نام و نام خانوادگی'),
        ),
    ]
