# Generated by Django 4.2.4 on 2023-08-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_alter_contactus_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(blank=True, default=0, max_length=250, verbose_name='نام و نام خانوادگی'),
            preserve_default=False,
        ),
    ]
