# Generated by Django 4.2.4 on 2023-08-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_alter_comment_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('sh', 'shiraz'), ('pr', 'paris'), ('mcs', 'manchester'), ('nyc', 'newyork')], default='nyc')),
            ],
        ),
    ]
