# Generated by Django 4.2.4 on 2023-08-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_cities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name': 'شهر', 'verbose_name_plural': 'شهرها'},
        ),
        migrations.RemoveField(
            model_name='cities',
            name='city',
        ),
        migrations.AddField(
            model_name='cities',
            name='name',
            field=models.CharField(default=0, max_length=250, verbose_name='موضوع'),
            preserve_default=False,
        ),
    ]
