# Generated by Django 4.2.4 on 2023-08-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_alter_cities_options_remove_cities_city_cities_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='city',
            field=models.CharField(default='SHIRAZ', max_length=25),
        ),
    ]
