# Generated by Django 4.2.4 on 2023-08-16 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_alter_cafe_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cities',
        ),
    ]
