# Generated by Django 4.2.4 on 2023-08-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_delete_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='city',
            field=models.CharField(choices=[('SHIRAZ', 'SH'), ('NEWYORK', 'NY'), ('MANCHESTER', 'MN')], default='SHIRAZ', max_length=25),
        ),
    ]
