# Generated by Django 4.2.4 on 2023-08-24 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
