# Generated by Django 4.2.4 on 2023-09-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_rename_post_image_cafe_alter_image_image_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created'], 'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='business_co_created_9bf774_idx',
        ),
        migrations.AddField(
            model_name='contactus',
            name='subject',
            field=models.CharField(default='', max_length=250, verbose_name='موضوع'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created'], name='business_co_created_095fe6_idx'),
        ),
    ]
