# Generated by Django 4.2.4 on 2023-09-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_likebutton'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeButton',
        ),
    ]
