# Generated by Django 4.2.4 on 2023-09-29 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_cafe_image_caption_cafe_like_count_cafe_likes_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.cafe')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
