# Generated by Django 4.2.4 on 2023-10-08 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_menu_section_menuitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'لایک', 'verbose_name_plural': 'لایک ها'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'منو', 'verbose_name_plural': 'منو ها'},
        ),
        migrations.AlterModelOptions(
            name='menuitems',
            options={'verbose_name': 'گزینه منو', 'verbose_name_plural': 'گزینه های منو'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AddField(
            model_name='menuitems',
            name='cafe',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='نام کافه'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='cafe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='business.cafe', verbose_name='کافه'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=250, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='price',
            field=models.FloatField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.section', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='section',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='business.menu'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=50, verbose_name='دسته'),
        ),
    ]
