# Generated by Django 4.2.4 on 2023-10-08 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0030_alter_like_options_alter_menu_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='business.cafe'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
