# Generated by Django 4.2.4 on 2023-10-13 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0032_menu_alter_section_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='cafe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='menu', serialize=False, to='business.cafe', verbose_name='کافه'),
        ),
        migrations.AlterField(
            model_name='menuitems',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='business.section', verbose_name='دسته بندی'),
        ),
    ]
