# Generated by Django 4.2.4 on 2023-10-13 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0033_alter_menu_cafe_alter_menuitems_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='cafe',
        ),
    ]
