# Generated by Django 4.2.4 on 2023-11-02 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0036_cafe_saved_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
