# Generated by Django 4.2.7 on 2023-11-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0037_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='cache',
            field=models.BooleanField(default=False),
        ),
    ]
