# Generated by Django 4.2.7 on 2023-11-17 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0038_cafe_cache'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='cache',
            new_name='refresh',
        ),
    ]
