# Generated by Django 4.2.7 on 2023-11-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0039_rename_cache_cafe_refresh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='refresh',
        ),
    ]
