# Generated by Django 4.2.7 on 2023-11-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0040_remove_cafe_refresh'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='refresh',
            field=models.BooleanField(default=False),
        ),
    ]
