# Generated by Django 4.2.4 on 2023-08-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='reading_time',
            field=models.PositiveIntegerField(blank=True, verbose_name='زمان مطالعه'),
        ),
    ]
