# Generated by Django 4.2.4 on 2023-08-26 04:24

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_comment_created_alter_comment_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=['top', 'left'], force_format=None, keep_meta=True, quality=100, scale=None, size=[500, 300], upload_to='post_images'),
        ),
    ]
