# Generated by Django 4.2.7 on 2023-11-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_account_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('نوشیدنی', 'نوشیدنی'), ('فست فود', 'فست فود'), ('غذای سنتی', 'غذای سنتی'), ('غذای فرنگی', 'غذای فرنگی')], default='سایر', max_length=20),
        ),
    ]
