# Generated by Django 4.2.7 on 2023-11-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('نوشیدنی', 'نوشیدنی'), ('فست فود', 'فست فود'), ('غذای سنتی', 'غذای سنتی'), ('غذای فرنگی', 'غذای فرنگی'), ('سایر', 'سایر')], default='سایر', max_length=20),
        ),
    ]
